version: '3.1'

services:
  seed:
    image: colinmollenhour/mariadb-galera-swarm
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - MYSQL_USER=user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - NODE_ADDRESS=^10.2.0.*
    networks:
      - backend
    command: seed
    volumes:
      - /docker/local/mysql/lib:/var/lib/mysql
    secrets:
      - xtrabackup_password
      - mysql_password
      - mysql_root_password
  node1:
    image: colinmollenhour/mariadb-galera-swarm
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - NODE_ADDRESS=^10.2.0.*
      - HEALTHY_WHILE_BOOTING=1
    networks:
      - backend
    command: node seed,node
    volumes:
      - /docker/local/mysql/node1/lib:/var/lib/mysql
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    secrets:
      - xtrabackup_password
  node2:
    image: colinmollenhour/mariadb-galera-swarm
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - NODE_ADDRESS=^10.2.0.*
      - HEALTHY_WHILE_BOOTING=1
    networks:
      - backend
    command: node seed,node
    volumes:
      - /docker/local/mysql/node2/lib:/var/lib/mysql
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    secrets:
      - xtrabackup_password
  node3:
    image: colinmollenhour/mariadb-galera-swarm
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - NODE_ADDRESS=^10.2.0.*
      - HEALTHY_WHILE_BOOTING=1
    networks:
      - backend
    command: node seed,node
    volumes:
      - /docker/local/mysql/node3/lib:/var/lib/mysql
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    secrets:
      - xtrabackup_password


volumes:
  mysql-data:
    driver: local

networks:
  backend:
    driver: overlay
    ipam:
      driver: default
      config:
      - subnet: 10.2.0.0/24


secrets:
  xtrabackup_password:
    file: .secrets/xtrabackup_password
  mysql_password:
    file: .secrets/mysql_password
  mysql_root_password:
    file: .secrets/mysql_root_password
