version: "3"

networks:
  prometheus:
    external:
      name: prometheus_backend
  elk:
    external:
      name: elk_backend
  traefik:
    external:
      name: traefik_public

services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - prometheus
      - traefik
      - elk
    volumes:
      - /docker/share/grafana:/var/lib/grafana
    environment:
      - PROMETHEUS_ENDPOINT=http://prometheus:9090
      - GF_SERVER_ROOT_URL=http://grafana.cretinon.fr
    labels:
      - "traefik.backend.loadbalancer.swarm=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:grafana.cretinon.fr"
      - "traefik.docker.network=traefik_public"
    deploy:
      mode: replicated
