version: '3.1'

services:
  proxy:
    image: perconalab/proxysql
    networks:
      backend:
        aliases:
          - proxy_db
    ports:
      - "3306:3306"
      - "6032:6032"
    environment:
      - CLUSTER_NAME=galera-15
      - ETCD_HOST=galera_etcd
      - DISCOVERY_SERVICE=galera_etcd:2379
      - MYSQL_ROOT_PASSWORD=s3cr3TL33tP@ssw0rd
      - MYSQL_PROXY_USER=proxyuser
      - MYSQL_PROXY_PASSWORD=s3cr3TL33tPr0xyP@ssw0rd
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=proxysql]
     # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      # placement constraint - in this case on 'worker' nodes only

  etcd:
    image: quay.io/coreos/etcd
    command:  etcd
    volumes:
      - /usr/share/ca-certificates/:/etc/ssl/certs
    environment:
      - ETCD_DATA_DIR=/opt/etcd/data
      - ETCD_NAME=etcd-node-01 
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
      - ETCD_ADVERTISE_CLIENT_URLS=http://galera_etcd:2379,http://galera_etcd:4001
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://galera_etcd:2380
      - ETCD-INITIAL-CLUSTER=etcd0=http://galera_etcd:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
    networks:
      backend:
        aliases:
          - galera_etcd
    deploy:
      mode: replicated
      replicas: 1

  percona-xtradb-cluster:
    image: percona/percona-xtradb-cluster:5.7
    networks:
      - backend
    environment:
      - DISCOVERY_SERVICE=galera_etcd:2379
      - CLUSTER_NAME=galera-15
      - MYSQL_ROOT_PASSWORD=s3cr3TL33tP@ssw0rd
    deploy:
      mode: global
      labels: [APP=pxc]
     # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      # placement constraint - in this case on 'worker' nodes only

networks:
  backend:
    driver: overlay
    ipam:
      driver: default
      config:
      - subnet: 10.2.0.0/24

