version: '3'

services:
  registry:
    image: registry:2
    ports:
      - "5001:5000"
    networks:
      - registry-net
    volumes:
      - /docker/share/registry:/var/lib/registry
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
networks:
  registry-net:
